## ----------------------------------------------------------------------------
## ..:: ocp-web installation ::..
## ----------------------------------------------------------------------------

## Installing ocp-web Server
- hosts: ocp-web
  remote_user: root
  tasks:

    - name: Set timezone to Europe/Rome
      timezone:
        name: Europe/Rome
        
    - name: Upgrading all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist
        
    - name: Remove resolv.conf link
      file:
        path: /etc/resolv.conf
        state: absent

    - name: Copy resolv.conf file
      copy:
        src: resolv.conf
        dest: /etc/resolv.conf

    - name: setting hostname
      template:
        src: hostname.j2
        dest: /etc/hostname

    ## TELEGRAF
    - name: Adding influx apt-key
      apt_key:
        url: https://repos.influxdata.com/influxdb.key
        state: present

    - name: Adding Influx apt reporisotries
      shell: echo "deb https://repos.influxdata.com/ubuntu `lsb_release -cs` stable\n" > /etc/apt/sources.list.d/influxdb.list

    - name: Upgrading all packages to the latest version
      apt:
        update_cache: yes
        upgrade: dist

    - name: Installing Telegraf
      apt:
        pkg:
        - telegraf

    - name: Copying Telegraf configuration file
      template:
        src: telegraf.conf.j2
        dest: /etc/telegraf/telegraf.conf

    ## Staring Telegraf Agent
    - name: Restarting Telegraf agent
      service:
        name: telegraf
        state: restarted

    ## Installing NGINX OSS 
    - name: installing nginx OSS
      apt:
        pkg:
        - nginx    

    - name: Copy nginx.conf files
      copy:
        src: ocp-web/
        dest: /etc/nginx/

    - name: starting nginx 
      service:
        name: nginx
        state: started

    - name: deleting nginx.conf original file
      file:
        path: /etc/nginx/nginx.conf
        state: absent

    - name: initial nginx config file
      file:
        src: /etc/nginx/nginx.conf-initial
        dest: /etc/nginx/nginx.conf
        state: link

    - name: enabling nginx at boot time
      service:
        name: nginx
        enabled: yes 

    - name: starting nginx 
      service:
        name: nginx
        state: restarted

    ## Installing k9s
    - name: Downloading -brew- installation file 
      get_url:
        url: https://raw.githubusercontent.com/Homebrew/install/master/install.sh
        dest: /home/ubuntu/install-k9s.sh
        mode: '0755'

    - name: Installing -brew-
      become: true
      become_user: ubuntu
      command: /bin/bash -c "echo'y' | /home/ubuntu/install-k9s.sh"
      args: 
         chdir: /home/ubuntu/

    - name: Adding -brew- bin dir to PATH
      lineinfile:
        path: /home/ubuntu/.profile
        line: PATH="$PATH:/home/linuxbrew/.linuxbrew/bin"

    - name: Installing k9s through Brew Package manager
      become: true
      become_user: ubuntu
      homebrew:
        name: derailed/k9s/k9s
        state: present
      environment:
        PATH: "{{ ansible_env.PATH }}:/home/linuxbrew/.linuxbrew/bin"




# ## ----------------------------------------------------------------------------
# ## ..:: ocp-allnodes perparation ::..
# ## ----------------------------------------------------------------------------

# ## Working on all nodes in the OCP Cluster
# - hosts: ocp-bootstrap
#   remote_user: root
#   tasks:

#     - name: download RHCOS Kernel from ocp-web
#       get_url:
#         url: https://10.1.1.8:8080/installations/rhcos-{{ rhcos_release }}-x86_64-live-kernel-x86_64
#         dest: /boot/vmlinuz-rhcos

#     - name: download RHCOS Initramfs from ocp-web
#       get_url:
#         url: https://10.1.1.8:8080/installations/rhcos-{{ rhcos_release }}-x86_64-live-initramfs.x86_64.img
#         dest: /boot/initramfs-rhcos.img

